# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 340d3ecbe2976a013348159061dd94c30eac8163185b420a5125819b3c9d48e70b9fbe4ab59f9eb8ddd8d75214e0b8985d7ba27eea00a01040968335b2f9e6b5

test:
  secret_key_base: f68569fc5eaf3204d786334b6ac01df0374651699ba80587f7c63121ecbb9f02c02983cd5ed690c410d8d013ac4304911ad6d0febdf040abbe59917b2de09620

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
